extraction:
  cpp:
    prepare:
      packages:
        - cargo
    after_prepare:
      - git clone --depth 1 https://github.com/OISF/libhtp.git
      - cargo install cbindgen
      - export PATH=/opt/work/.cargo/bin:$PATH
